Refactor MockServer: Use Popen with Twisted
Prior to this commit, running the tests could result in the following
exception:
"exceptions.AttributeError: '_SIGCHLDWaker' object has no attribute 'doWrite'"
This exception occurs due to Twisted's incompatibility with
multiprocessing. Therefore, this commit introduces the use of Popen
instead of multiprocessing to prevent such errors from arising.

Refs:
https://github.com/scrapy/scrapy/issues/2499